# Generated by Django 5.0.3 on 2024-10-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
