# Generated by Django 5.0.3 on 2024-10-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_name_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
