# Generated by Django 5.0.3 on 2024-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='body',
            new_name='description',
        ),
    ]
