# Generated by Django 5.0.3 on 2024-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_gallerymedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymedia',
            name='video_url',
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery_videos/'),
        ),
    ]
